CREATE SCHEMA IF NOT EXISTS client_portal;

CREATE TABLE IF NOT EXISTS client_portal.client_portals (
    id VARCHAR(36) PRIMARY KEY,
    external_client_id VARCHAR(80) NOT NULL UNIQUE,
    client_name VARCHAR(255) NOT NULL,
    case_number VARCHAR(120),
    case_type VARCHAR(160),
    stage VARCHAR(120),
    responsible_name VARCHAR(160),
    visible_sections JSONB NOT NULL DEFAULT '{}'::jsonb,
    token_version INTEGER NOT NULL DEFAULT 1,
    revoked_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    created_by VARCHAR(160) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS client_portals_external_client_idx
    ON client_portal.client_portals (external_client_id);

CREATE TABLE IF NOT EXISTS client_portal.portal_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portal_id VARCHAR(36) NOT NULL REFERENCES client_portal.client_portals(id) ON DELETE CASCADE,
    source_ref VARCHAR(160) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    occurred_label VARCHAR(80),
    visible_to_client BOOLEAN NOT NULL DEFAULT FALSE,
    published_by VARCHAR(160),
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT portal_updates_source_unique UNIQUE (portal_id, source_ref)
);

CREATE INDEX IF NOT EXISTS portal_updates_visible_idx
    ON client_portal.portal_updates (portal_id, visible_to_client);

CREATE TABLE IF NOT EXISTS client_portal.portal_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portal_id VARCHAR(36) NOT NULL REFERENCES client_portal.client_portals(id) ON DELETE CASCADE,
    action VARCHAR(60) NOT NULL,
    actor VARCHAR(160) NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS portal_audit_events_portal_idx
    ON client_portal.portal_audit_events (portal_id, created_at DESC);

CREATE TABLE IF NOT EXISTS client_portal.portal_access_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portal_id VARCHAR(36) NOT NULL REFERENCES client_portal.client_portals(id) ON DELETE CASCADE,
    visitor_fingerprint CHAR(64) NOT NULL,
    accessed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS portal_access_events_portal_idx
    ON client_portal.portal_access_events (portal_id, accessed_at DESC);
